### ISSUE TITLE
question

### ISSUE THREAD

**Issue by patatetom** [doukremt/distance#9]
hi,

I use [blockhash](https://github.com/commonsmachinery/blockhash-python) that returns strings of 64 characters corresponding to 256 bits (eg. 3fc03f803fc03f861f063f861f861f0e1f0f160f3e0f301f7e3f3e3f003f0038 for example) : for best results, can the string be used directly or must it be converted beforehand ?

thanks for the advice, lacsaP.

**Comment by pquentin** [comment]
Hello Pascal! Well it depends if you want to see a distance on individual bits or on hexadecimal characters. Did you have something else in mind?

**Comment by patatetom** [comment]
hello Quentin, I discover these concepts : will the distance be more accurate if it is calculated from bits ?

**Comment by pquentin** [comment]
Note that for fixed strings like this you want the Hamming distance and not the Levenshtein distance. I think you know that but just did not says so.

Yes, it will be more accurate on individual bits than with the hexadecimal representation, because with the hexadecimal representation even if a single bit changes then all 16 bits will be considered as different. http://blockhash.io/ also mentions that the intended use is to compute the number of bits that differ.

**Comment by pquentin** [comment]
Note that you don't need a library to compute a hamming distance on bits. See https://stackoverflow.com/q/26122368 for example.

**Comment by patatetom** [comment]
I'm closing this issue that wasn't really one. thank you for that clarification Quentin.
